version: "3"

services:
  ckan:
    volumes:
      - ./dev_config.ini:/etc/ckan/production.ini
      - ../ckanext-superset:/etc/ckanext-superset
      - ../ckanext-ukraine:/etc/ckanext-ukraine
      - ./ckan-entrypoint.sh:/ckan-entrypoint.sh
    command: ["ckan-paster","serve","--reload", "/etc/ckan/production.ini"]