version: "3"

volumes:
  ckan_storage:
  pg_data:

services:
  ckan:
    container_name: ckan
    build:
      context: ../
      dockerfile: adx_develop/ckan/Dockerfile
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=50
      - CKAN_SMTP_USER=${CKAN_SMTP_USER}
      - CKAN_SMTP_PASSWORD=${CKAN_SMTP_PASSWORD}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800/
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ckan_storage:/var/lib/ckan
      - ../:/usr/lib/adx
      - ../ckan:/usr/lib/ckan/venv/src/ckan
      - ./ckan/adx_config.ini:/etc/ckan/ckan.ini
      - ./ckan/adx_who.ini:/etc/ckan/who.ini
      - ./ckan/utils/:/adx_utils
      - ./ckan/ckan-entrypoint-adx.sh:/ckan-entrypoint.sh
    command: ["ckan","--config","/etc/ckan/ckan.ini", "run", "--host", "0.0.0.0"]
  supervisor:
    container_name: supervisor
    build:
      context: ../
      dockerfile: adx_develop/ckan/Dockerfile
    depends_on:
      - ckan
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800/
    volumes:
      - ckan_storage:/var/lib/ckan
      - ../:/usr/lib/adx
      - ../ckan:/usr/lib/ckan/venv/src/ckan
      - ./ckan/adx_config.ini:/etc/ckan/ckan.ini
      - ./ckan/adx_who.ini:/etc/ckan/who.ini
      - ./ckan/ckan_supervisor.conf:/etc/supervisor/conf.d/ckan_supervisor.conf
      - ./ckan/ckan-entrypoint-adx.sh:/ckan-entrypoint.sh
    entrypoint: ["/wait-for-it.sh", "ckan:5000", "--timeout=0",  "--", "/ckan-entrypoint.sh"]
    command: ["/usr/bin/supervisord"]

  cron:
    container_name: cron
    build: cron
    environment:
      # Set the ADX_SYSADMIN_API_KEY env var on the host to auto send emails
      - SECRET_ENVS={"ADX_SYSADMIN_API_KEY":"${ADX_SYSADMIN_API_KEY}"}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../ckan:/usr/lib/ckan/venv/src/ckan

  datapusher:
    build:
      context: ../datapusher
    container_name: datapusher
    volumes:
      - ../datapusher:/var/www/datapusher
    ports:
      - "8800:8800"

  db:
    container_name: db
    ports:
      - "5432:5432"
    build:
      context: ../ckan/
      dockerfile: contrib/docker/postgresql/Dockerfile
      args:
        - DS_RO_PASS=datastore
        - POSTGRES_PASSWORD=ckan
    environment:
      - DS_RO_PASS=datastore
      - POSTGRES_PASSWORD=ckan
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    ports:
      - "8983:8983"
    build:
      context: .
      dockerfile: solr/Dockerfile
      args:
        - BUILD_CONTEXT=.
    environment:
      - SOLR_LOG_LEVEL=WARN

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    image: redis:latest
