# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  ckan_storage:
  pg_data:

services:
  ckan:
    container_name: ckan
    build:
      context: ../
      dockerfile: adx_develop/ckan/Dockerfile
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - CKAN_SMTP_USER=${CKAN_SMTP_USER}
      - CKAN_SMTP_PASSWORD=${CKAN_SMTP_PASSWORD}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800/
    volumes:
      - ckan_storage:/var/lib/ckan
      - ../:/usr/lib/adx
      - ../ckan:/usr/lib/ckan/venv/src/ckan
      - ./ckan/adx_config.ini:/etc/ckan/production.ini
      - ./ckan/adx_who.ini:/etc/ckan/who.ini
      - ./ckan/utils/:/adx_utils
    command: ["ckan-paster","serve","--reload", "/etc/ckan/production.ini"]

  supervisor:
    container_name: supervisor
    build:
      context: ../
      dockerfile: adx_develop/ckan/Dockerfile
    links:
      - db
      - solr
      - redis
    environment:
#      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800/
    volumes:
      - ckan_storage:/var/lib/ckan
      - ../:/usr/lib/adx
      - ../ckan:/usr/lib/ckan/venv/src/ckan
      - ./ckan/adx_config.ini:/etc/ckan/production.ini
      - ./ckan/ckan_supervisor_harvester.conf:/etc/supervisor/conf.d/ckan_harvester.conf
    command: ["/usr/bin/supervisord"]

  cron:
    container_name: cron
    build: cron
    environment:
      # Set the ADX_SYSADMIN_API_KEY env var on the host to auto send emails
      - SECRET_ENVS={"ADX_SYSADMIN_API_KEY":"${ADX_SYSADMIN_API_KEY}"}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../ckan:/usr/lib/ckan/venv/src/ckan

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    container_name: db
    ports:
      - "5432:5432"
    build:
      context: ../ckan/
      dockerfile: contrib/docker/postgresql/Dockerfile
      args:
        - DS_RO_PASS=datastore
        - POSTGRES_PASSWORD=ckan
    environment:
      - DS_RO_PASS=datastore
      - POSTGRES_PASSWORD=ckan
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: ../ckan/
      dockerfile: contrib/docker/solr/Dockerfile
    environment:
      - SOLR_LOG_LEVEL=WARN

  redis:
    container_name: redis
    image: redis:latest
