# Production environment overrides
# Merged with base.ini at container startup

[app:main]
ckanext.blob_storage.storage_service_url = https://p-giftless-e5eeh9gnhegzhed0.z01.azurefd.net

ckanext.saml2auth.idp_metadata.remote_url = https://auth-hivtools.unaids.org/samlp/metadata/M3TzWiL728R3iQz3dpSy6dAsYMbtUm6T
