# Staging environment overrides
# Merged with base.ini at container startup

[app:main]
ckanext.blob_storage.storage_service_url = https://s-giftless-frgxc2hfd9dretb8.z01.azurefd.net

## SMTP via Azure Communication Services
smtp.server = smtp.azurecomm.net:587
smtp.starttls = true
smtp.mail_from = admin@adr-s.fjelltopp.org
