name: Build and publish CKAN image

on: 
  push:
    paths:
      - 'ckan/**'
      - '.github/workflows/build_ckan.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo

    - name: Build and publish CKAN base image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: ckan_development
        image-tag: ${{ github.ref_name }}
        build-context: ckan/
        dockerfile: ckan/Dockerfile
